export const MAIN_MENU_NEW_REQUEST = 'MAIN_MENU_NEW_REQUEST';
export const MAIN_MENU_NEW_SUCCESS = 'MAIN_MENU_NEW_SUCCESS';
export const MAIN_MENU_NEW_FAIL = 'MAIN_MENU_NEW_FAIL';
export const MAIN_MENU_NEW_RESET = 'MAIN_MENU_NEW_RESET';

export const MAIN_MENU_ALL_REQUEST = 'MAIN_MENU_ALL_REQUEST';
export const MAIN_MENU_ALL_SUCCESS = 'MAIN_MENU_ALL_SUCCESS';
export const MAIN_MENU_ALL_FAIL = 'MAIN_MENU_ALL_FAIL';

export const MAIN_MENU_BY_ID_REQUEST = 'MAIN_MENU_BY_ID_REQUEST';
export const MAIN_MENU_BY_ID_SUCCESS = 'MAIN_MENU_BY_ID_SUCCESS';
export const MAIN_MENU_BY_ID_FAIL = 'MAIN_MENU_BY_ID_FAIL';
export const MAIN_MENU_BY_ID_RESET = 'MAIN_MENU_BY_ID_RESET';

export const MAIN_MENU_UPDATE_BY_ID_REQUEST = 'MAIN_MENU_UPDATE_BY_ID_REQUEST';
export const MAIN_MENU_UPDATE_BY_ID_SUCCESS = 'MAIN_MENU_UPDATE_BY_ID_SUCCESS';
export const MAIN_MENU_UPDATE_BY_ID_FAIL = 'MAIN_MENU_UPDATE_BY_ID_FAIL';
export const MAIN_MENU_UPDATE_BY_ID_RESET = 'MAIN_MENU_UPDATE_BY_ID_RESET';

export const MAIN_MENU_DELETE_REQUEST = 'MAIN_MENU_DELETE_REQUEST';
export const MAIN_MENU_DELETE_SUCCESS = 'MAIN_MENU_DELETE_SUCCESS';
export const MAIN_MENU_DELETE_FAIL = 'MAIN_MENU_DELETE_FAIL';
