export const MOVIE_NEW_REQUEST = 'MOVIE_NEW_REQUEST';
export const MOVIE_NEW_SUCCESS = 'MOVIE_NEW_SUCCESS';
export const MOVIE_NEW_FAIL = 'MOVIE_NEW_FAIL';
export const MOVIE_NEW_RESET = 'MOVIE_NEW_RESET';

export const MOVIE_ALL_REQUEST = 'MOVIE_ALL_REQUEST';
export const MOVIE_ALL_SUCCESS = 'MOVIE_ALL_SUCCESS';
export const MOVIE_ALL_FAIL = 'MOVIE_ALL_FAIL';

export const MOVIE_BY_ID_REQUEST = 'MOVIE_BY_ID_REQUEST';
export const MOVIE_BY_ID_SUCCESS = 'MOVIE_BY_ID_SUCCESS';
export const MOVIE_BY_ID_FAIL = 'MOVIE_BY_ID_FAIL';
export const MOVIE_BY_ID_RESET = 'MOVIE_BY_ID_RESET';

export const MOVIE_UPDATE_BY_ID_REQUEST = 'MOVIE_UPDATE_BY_ID_REQUEST';
export const MOVIE_UPDATE_BY_ID_SUCCESS = 'MOVIE_UPDATE_BY_ID_SUCCESS';
export const MOVIE_UPDATE_BY_ID_FAIL = 'MOVIE_UPDATE_BY_ID_FAIL';
export const MOVIE_UPDATE_BY_ID_RESET = 'MOVIE_UPDATE_BY_ID_RESET';

export const MOVIE_DELETE_REQUEST = 'MOVIE_DELETE_REQUEST';
export const MOVIE_DELETE_SUCCESS = 'MOVIE_DELETE_SUCCESS';
export const MOVIE_DELETE_FAIL = 'MOVIE_DELETE_FAIL';
